kind: Pod
apiVersion: v1 
metadata: 
  name: expenseconfig
  labels:
    env: Dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: age
        valueFrom:
          configMapKeyRef:
            name: expenseconfig
            key: name
            