apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Expense 
  region: us-east-1       

managedNodeGroups:
  - name: expense         
    instanceType: ["m5.large", "m5a.large", "m4.large", "t3.large"]
    spot : true
    desiredCapacity: 3     
    minSize: 1              
    maxSize: 4              